name: rag-enterprise
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9.11
  - pandas=2.2.3
  - requests=2.32.3
  - faiss-gpu=1.9.0              
  - sentence-transformers=4.1.0
  - glob2=0.7
  - streamlit=1.45.1
  - python-dotenv=1.1.0
  - pip
  - pip:
    - langchain==0.3.25
    - langchain-google-genai==2.1.4
    - langchain_openai==0.3.18
    - langchain_community==0.3.24
    - langchain_experimental==0.3.4
    - langchain-huggingface==0.2.0
    - tabulate==0.9.0
    - transformers==4.52.3
    - sentencepiece==0.2.0
    - huggingface_hub==0.32.0
    - langchain-ollama==0.3.3
    - ipykernel==6.29.5 
    - python-gitlab==5.6.0
    # GPU-first PyTorch with automatic CPU fallback
    - torch==2.7.0+cu126
    - torchvision==0.22.0+cu126
    - torchaudio==2.7.0+cu126
    - --extra-index-url https://download.pytorch.org/whl/cu126
  