apiVersion: v1
kind: Service
metadata:
  name: streamlit-ollama-service
spec:
  selector:
    app: streamlit-ollama-app
  ports:
    - name: http # Name for the Streamlit port
      protocol: TCP
      port: 80              # Publicly accessible port
      targetPort: 8501      # Streamlit's container port
    - name: ollama # Name for the Ollama port
      protocol: TCP
      port: 11434           # Publicly accessible port
      targetPort: 11434     # Ollama's container port
  type: LoadBalancer
